name: Build and Deploy Docs
description: Generates documentation and deploys to GitHub Pages.

inputs:
  build_playground:
    description: 'Set to "true" to copy the Nuxt playground output as a demo.'
    required: false
    default: "false"
  build_demo:
    description: 'Set to "true" to install deps and copy a demo/ directory.'
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - run: pnpm doc
      shell: bash

    - name: Copy Playground Demo
      if: "inputs.build_playground == 'true'"
      shell: bash
      run: |
        if [ -d "playground" ]; then
          cp -r playground/.output/public docs/demo
        fi

    - name: Copy Demo
      if: "inputs.build_demo == 'true'"
      shell: bash
      run: |
        if [ -d "demo" ]; then
          pushd demo && pnpm i --frozen-lockfile && popd
          cp -r demo/dist docs/demo
        fi

    - name: Documentation
      uses: crazy-max/ghaction-github-pages@v4
      with:
        jekyll: false
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
