name: Docs

env:
  USE_LOCKFILE: ${{ vars.USE_LOCKFILE }}
  ENABLE_DOCS: ${{ vars.ENABLE_DOCS }}

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ docs ]

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*"]
    steps:
      - uses: actions/checkout@v6
        if: "env.ENABLE_DOCS == 'true'"

      - name: Setup
        uses: alanscodelog/actions/.github/actions/setup@main
        if: "env.ENABLE_DOCS == 'true'"
        with:
          USE_LOCKFILE: ${{ env.USE_LOCKFILE }}
          # INSTALL_PLAYWRIGHT: true

      - name: Build
        uses: alanscodelog/actions/.github/actions/build@main
        if: "env.ENABLE_DOCS == 'true'"

      - name: Deploy Docs
        uses: alanscodelog/actions/.github/actions/docs@main
        if: "env.ENABLE_DOCS == 'true'"
        with:
          build_playground: "false"
          build_demo: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
