name: Build
# not technically necessary because release also runs tests but this way the build badge is separate

on:
  #TOCONFIGURE
  schedule:
    # every first of the month at 12:00 noon GMT-3
    # https://crontab.guru/#0_12_1_*_*
    - cron:  '0 15 1 * *'
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ build ]
    # to trigger: curl -v -H "Accept: application/vnd.github.everest-preview+json" -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/alanscodelog/TOREPONAME/dispatches -d '{ "event_type": "build" }'

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
     - name: Extract branch name
       run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
       id: extracted
     - name: Extract branch name 2
       run: echo '::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})'
       id: extracted2
     - name: Extract branch name 3
       run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
       id: extracted3
   
     - run: echo ${{ github.ref }}
     - run: echo ${GITHUB_REF#refs/heads/}
     - run: echo ${{ steps.extracted.outputs.branch }} 
     - run: echo ${{ steps.extracted2.outputs.branch }}
     - run: echo ${{ steps.extracted3.outputs.branch }}
      
     - name: Test1
       if: "! contains(${GITHUB_REF#refs/heads/}, 'master')"
       run: echo not on master
      
  
