name: Build

on:
  push:
    branches: [ master, beta ]
    
jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
     - name: Extract branch name
       run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
       id: extracted_branch
 
     - run: echo ${{ steps.extracted_branch.outputs.branch }} 
      
     - name: Test1
       if: "! contains(steps.extracted_branch.outputs.branch, 'master')"
       run: exit 1
      
     - name: Test1
       if: "contains(steps.extracted_branch.outputs.branch, 'master')"
       run: echo on master
